site_name: {{ cookiecutter.cookiecutter_name }}
theme:
  name: material

copyright: |
  &copy; 2024 <a href="https://github.com/{{cookiecutter.github_username}}"  target="_blank" rel="noopener">{{cookiecutter.full_name}}</a>
